#if TARGET_OS_SIMULATOR
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CheetahLoyaltyUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSBundle;
@class NSCoder;

/// A view controller that can be initialized with a specified nib name or a nib named the same as its class name.
/// The bundle for the nib is found by the <code>bundle(forFileName:)</code> extension method of <code>Bundle</code>.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI17NibViewController")
@interface NibViewController : UIViewController
- (void)viewDidLoad;
/// Returns a newly initialized nib view controller with the nib file named the same as its class name in the bundle retruned by the <code>bundle(forFileName:)</code> extension method of <code>Bundle</code>.
/// <em>A subclass can implement a superclass designated initializer as a subclass convenience initializer</em> as stated in the Automatic Initializer Inheritance of the <em>Swift Language Guide</em>
/// seealso:
/// <a href="https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID222">Automatic Initializer Inheritance</a>
///
/// returns:
/// A newly initialized <code>NibViewController</code> object.
- (nonnull instancetype)init;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

/// A container <code>NibViewController</code> that contains an <code>AlertEmbeddableViewController</code>
SWIFT_CLASS("_TtC16CheetahLoyaltyUI19AlertViewController")
@interface AlertViewController : NibViewController
/// View container for non-full screen <code>AlertEmbeddableViewController</code>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end





@class NSLayoutConstraint;
@class UIImageView;
@class UILabel;

SWIFT_CLASS("_TtC16CheetahLoyaltyUI21AppInfoViewController")
@interface AppInfoViewController : NibViewController
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified logoImageViewHeightConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified logoImageViewAspectRatioConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified logoImageViewTopSpaceConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified descriptionLabelTopSpaceConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified infoLabelTopSpaceConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified infoLabelBottomSpaceConstraint;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified backgroundImageView;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified logoImageView;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified descriptionLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified infoLabel;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




/// A CollectionViewFlowLayout that resembles a carousel.
/// This flow layout mimics a carousel layout.
/// It has <code>minimumLineSpacing</code> and <code>minimumInteritemSpacing</code> set to 0.
/// The <code>itemSize</code> is set equal to the collection view’s frame size.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI32CarouselCollectionViewFlowLayout")
@interface CarouselCollectionViewFlowLayout : UICollectionViewFlowLayout
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
@end


/// A general collection view cell for carousel content.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI16CarouselItemCell")
@interface CarouselItemCell : UICollectionViewCell
/// An image view for the content.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
/// A container view for the content.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
/// A container view for the title label.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified titleContainerView;
/// The title label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI15SelectionButton")
@interface SelectionButton : UIButton
@property (nonatomic, getter=isSelected) BOOL selected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (CGRect)imageRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (CGRect)titleRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (void)didTapButton;
- (void)groupStateDidChange:(NSNotification * _Nonnull)notification;
@end


/// A custom <code>UIButton</code> that serves as a check box by using an image
/// Important: According to apple’s ios HIG, the size of the image should
/// be approriate to its container or it will be displayed undesirably
SWIFT_CLASS("_TtC16CheetahLoyaltyUI8CheckBox")
@interface CheckBox : SelectionButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// A <code>NibViewController</code> subclass that manages and displays states of content.
/// This view controller handles states of loading content by displaying the appropriate child view controller depending of the state.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI22StatefulViewController")
@interface StatefulViewController : NibViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStackView;
@class UISearchBar;
@class UICollectionView;
@protocol UIViewControllerTransitionCoordinator;
@class UIRefreshControl;

/// A <code>StatefulViewController</code> subclass that manages a collection view.
/// This class has an associated value depending on the associated value of its collection view controller.
/// A refresh control is added in the collection view to capture pull to refresh events which will call the <code>refreshContent(completion:)</code> of the collection controller.
/// If there is an error during the refresh, the <code>showRefreshError(title:, message:)</code> by default will show an alert with the error information.
/// The localize description of the error will be passed as the message with no title.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI24CollectionViewController")
@interface CollectionViewController : StatefulViewController
/// A stack view that holds both the collection view and search bar container view.
/// The stack view’s axis is set to vertical by default.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified containerStackView;
/// The search bar.
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
/// The collection view.
@property (nonatomic, strong) IBOutlet UICollectionView * _Null_unspecified collectionView;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)refreshControlValueChanged:(UIRefreshControl * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The default collection view cell used by the <code>CountriesCollectionController</code> to display the list of countries.
/// This cell contains a single label that is used to display the name of the country.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI25CountryCollectionViewCell")
@interface CountryCollectionViewCell : UICollectionViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified nameLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIActivityIndicatorView;

/// A <code>NibViewController</code> subclass conforming to the <code>LoadableViewController</code>.
/// This view controller is the default design for a loading view controller.
/// It has an activity indicator and a label for a loading message.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI28DefaultLoadingViewController")
@interface DefaultLoadingViewController : NibViewController
/// The activity indicator.
@property (nonatomic, strong) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
/// The loading label
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified loadingLabel;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A <code>NibViewController</code> subclass conforming to the <code>ReloadableViewController</code>.
/// This view controller is the default design for a reload view controller.
/// It has a label for a reload message and a button to execute the reload.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI27DefaultReloadViewController")
@interface DefaultReloadViewController : NibViewController
/// The container of the label and button.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified containerStackView;
/// The reload message label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified messageLabel;
/// The retry button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified retryButton;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

/// A <code>StatefulViewController</code> subclass that manages a generic detail view.
/// This view controller serves as the base design of a detail view.
/// An object conforming to the <code>DetailController</code> protocol is the data provider and action handler of this view controller.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI20DetailViewController")
@interface DetailViewController : StatefulViewController
@property (nonatomic, strong) IBOutlet UIScrollView * _Null_unspecified scrollView;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified labelStackView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified headingLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified subheadingLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified bodyLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified pointsLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified periodLabel;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified actionButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayoutAttributes;

/// A CollectionViewFlowLayout that resembles a table view with dynamic height sizing.
/// This flow layout mimics a table view layout with dynamic height sizing.
/// It has <code>minimumLineSpacing</code> and <code>minimumInteritemSpacing</code> set to 10.
/// Collection view cells used in this layout must override the <code>preferredLayoutAttributesFitting(_:)</code> method to calculate the appropriate height for the cell. One way of doing this is the following:
/// \code
/// override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
///     let layoutAttributes = super.preferredLayoutAttributesFitting(layoutAttributes)
///     layoutIfNeeded()
///     layoutAttributes.frame.size = systemLayoutSizeFitting(UIView.layoutFittingCompressedSize,
///                                                           withHorizontalFittingPriority: .required,
///                                                           verticalFittingPriority: .fittingSizeLevel)
///     return layoutAttributes
/// }
///
/// \endcode
SWIFT_CLASS("_TtC16CheetahLoyaltyUI35DynamicListCollectionViewFlowLayout")
@interface DynamicListCollectionViewFlowLayout : UICollectionViewFlowLayout
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

SWIFT_CLASS("_TtC16CheetahLoyaltyUI17FloatingTextField")
@interface FloatingTextField : UITextField
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic) NSTextAlignment textAlignment;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isEnabled) BOOL enabled;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI25FloatingTextFieldWithIcon")
@interface FloatingTextFieldWithIcon : FloatingTextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI15GrowingTextView")
@interface GrowingTextView : UIScrollView
@property (nonatomic, strong) UIView * _Nullable inputView;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic, readonly) BOOL isFirstResponder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)reloadInputViews;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI16FloatingTextView")
@interface FloatingTextView : GrowingTextView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


/// An <code>AlertEmbeddableViewController</code> that can display
/// a heading message, a subheading message, and a dynamic count of buttons in a <code>UIStackView</code>
SWIFT_CLASS("_TtC16CheetahLoyaltyUI26GenericAlertViewController")
@interface GenericAlertViewController : NibViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headingLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subheadingLabel;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@class UIImagePickerController;

/// A wrapper class setting up the presentation of an <code>UIImagePickerController</code> by a designated view controller. This wrapper class only accepts media types of image or movie.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI20ImagePickerPresenter")
@interface ImagePickerPresenter : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A CollectionViewFlowLayout that resembles a table view.
/// This flow layout mimics a table view layout.
/// It has <code>minimumLineSpacing</code> and <code>minimumInteritemSpacing</code> set to 10.
/// The <code>itemSize</code> is set with the width equal to the collection view frame width minus the left and right section inset,
/// and the height set as the <code>cellHeight</code> property.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI28ListCollectionViewFlowLayout")
@interface ListCollectionViewFlowLayout : UICollectionViewFlowLayout
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
@end


/// A general collection view cell for list content.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI12ListItemCell")
@interface ListItemCell : UICollectionViewCell
/// A container view for all elements except for the activitiy indicator.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
/// An image view for the content.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
/// A stack view holding the title and subtitle label.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified contentStackView;
/// The title label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
/// The subtitle label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified subtitleLabel;
/// A general action button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified actionButton;
/// An activity Indicator for loading content.
@property (nonatomic, strong) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC16CheetahLoyaltyUI26LoadingAlertViewController")
@interface LoadingAlertViewController : NibViewController
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activitityIndicatorView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified loadingLabel;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// This is the default collection view cell used by the <code>MenuCollectionController</code> to display the list of Menu.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI12MenuItemCell")
@interface MenuItemCell : UICollectionViewCell
/// An image view for the content.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified image;
/// The name label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified name;
/// A container view for the name label.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified nameContainerView;
/// A stack view for the menu list.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified menuStackView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A subclass of <code>CollectionViewController</code> that shows a list of menu items with a log out button.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI18MenuViewController")
@interface MenuViewController : CollectionViewController
/// The log out button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified logOutButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



/// A subclass of <code>CheckBox</code> that serves as a radio button
/// that has an event listener/emitter to other radio buttons
/// within the same group
SWIFT_CLASS("_TtC16CheetahLoyaltyUI11RadioButton")
@interface RadioButton : CheckBox
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// A custom <code>UIButton</code>that serves as a rating button
/// that has an event listener/emitter to other rating buttons
/// within the same group
SWIFT_CLASS("_TtC16CheetahLoyaltyUI12RatingButton")
@interface RatingButton : SelectionButton
- (void)didTapButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;
@class AVCaptureConnection;

/// A <code>NibViewController</code> subclass that scans codes using the device’s camera.
/// This view controller captures codes from the device’s camera.
/// The code is then passed into the <code>captureAction</code> closure property.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI21ScannerViewController")
@interface ScannerViewController : NibViewController <AVCaptureMetadataOutputObjectsDelegate>
- (void)viewDidLayoutSubviews;
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UISegmentedControl;

/// A <code>NibViewController</code> subclass that manages segmented views.
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
/// This includes a segmented control that receives value changed events to change the shown view inside its container view.
/// Data and selection actions are managed by an object conforming to <code>SegmentedController</code> which is assigned to the <code>segmentedController</code> property.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI23SegmentedViewController")
@interface SegmentedViewController : NibViewController
/// The segmented control.
@property (nonatomic, strong) IBOutlet UISegmentedControl * _Null_unspecified segmentedControl;
/// The content view.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



/// The default collection view cell used by the <code>StatesCollectionController</code> to display the list of states.
/// This cell contains a single label that is used to display the name/label of the state.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI23StateCollectionViewCell")
@interface StateCollectionViewCell : UICollectionViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified nameLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





















































/// An <code>AlertEmbeddableViewController</code> that displays
/// a full screen view that forces/asks the user to upgrade the application to its current version
SWIFT_CLASS("_TtC16CheetahLoyaltyUI26UpgradeCheckViewController")
@interface UpgradeCheckViewController : NibViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified messageTextView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified upgradeNowButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified upgradeLaterButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified photoImageView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class WKNavigation;

/// A <code>NibViewController</code> subclass that displays web content.
/// This view controller holds a <code>WKWebView</code> and a <code>UIProgressView</code>.
/// The progress view is only shown when the web view is loading content.
/// This view controller also conforms to <code>WKNavigationDelegate</code>.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI17WebViewController")
@interface WebViewController : NibViewController <WKNavigationDelegate>
/// The web view.
@property (nonatomic, strong) IBOutlet WKWebView * _Null_unspecified webView;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#else
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CheetahLoyaltyUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSBundle;
@class NSCoder;

/// A view controller that can be initialized with a specified nib name or a nib named the same as its class name.
/// The bundle for the nib is found by the <code>bundle(forFileName:)</code> extension method of <code>Bundle</code>.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI17NibViewController")
@interface NibViewController : UIViewController
- (void)viewDidLoad;
/// Returns a newly initialized nib view controller with the nib file named the same as its class name in the bundle retruned by the <code>bundle(forFileName:)</code> extension method of <code>Bundle</code>.
/// <em>A subclass can implement a superclass designated initializer as a subclass convenience initializer</em> as stated in the Automatic Initializer Inheritance of the <em>Swift Language Guide</em>
/// seealso:
/// <a href="https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID222">Automatic Initializer Inheritance</a>
///
/// returns:
/// A newly initialized <code>NibViewController</code> object.
- (nonnull instancetype)init;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

/// A container <code>NibViewController</code> that contains an <code>AlertEmbeddableViewController</code>
SWIFT_CLASS("_TtC16CheetahLoyaltyUI19AlertViewController")
@interface AlertViewController : NibViewController
/// View container for non-full screen <code>AlertEmbeddableViewController</code>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end





@class NSLayoutConstraint;
@class UIImageView;
@class UILabel;

SWIFT_CLASS("_TtC16CheetahLoyaltyUI21AppInfoViewController")
@interface AppInfoViewController : NibViewController
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified logoImageViewHeightConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified logoImageViewAspectRatioConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified logoImageViewTopSpaceConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified descriptionLabelTopSpaceConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified infoLabelTopSpaceConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified infoLabelBottomSpaceConstraint;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified backgroundImageView;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified logoImageView;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified descriptionLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified infoLabel;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




/// A CollectionViewFlowLayout that resembles a carousel.
/// This flow layout mimics a carousel layout.
/// It has <code>minimumLineSpacing</code> and <code>minimumInteritemSpacing</code> set to 0.
/// The <code>itemSize</code> is set equal to the collection view’s frame size.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI32CarouselCollectionViewFlowLayout")
@interface CarouselCollectionViewFlowLayout : UICollectionViewFlowLayout
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
@end


/// A general collection view cell for carousel content.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI16CarouselItemCell")
@interface CarouselItemCell : UICollectionViewCell
/// An image view for the content.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
/// A container view for the content.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
/// A container view for the title label.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified titleContainerView;
/// The title label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI15SelectionButton")
@interface SelectionButton : UIButton
@property (nonatomic, getter=isSelected) BOOL selected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (CGRect)imageRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (CGRect)titleRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (void)didTapButton;
- (void)groupStateDidChange:(NSNotification * _Nonnull)notification;
@end


/// A custom <code>UIButton</code> that serves as a check box by using an image
/// Important: According to apple’s ios HIG, the size of the image should
/// be approriate to its container or it will be displayed undesirably
SWIFT_CLASS("_TtC16CheetahLoyaltyUI8CheckBox")
@interface CheckBox : SelectionButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// A <code>NibViewController</code> subclass that manages and displays states of content.
/// This view controller handles states of loading content by displaying the appropriate child view controller depending of the state.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI22StatefulViewController")
@interface StatefulViewController : NibViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStackView;
@class UISearchBar;
@class UICollectionView;
@protocol UIViewControllerTransitionCoordinator;
@class UIRefreshControl;

/// A <code>StatefulViewController</code> subclass that manages a collection view.
/// This class has an associated value depending on the associated value of its collection view controller.
/// A refresh control is added in the collection view to capture pull to refresh events which will call the <code>refreshContent(completion:)</code> of the collection controller.
/// If there is an error during the refresh, the <code>showRefreshError(title:, message:)</code> by default will show an alert with the error information.
/// The localize description of the error will be passed as the message with no title.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI24CollectionViewController")
@interface CollectionViewController : StatefulViewController
/// A stack view that holds both the collection view and search bar container view.
/// The stack view’s axis is set to vertical by default.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified containerStackView;
/// The search bar.
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
/// The collection view.
@property (nonatomic, strong) IBOutlet UICollectionView * _Null_unspecified collectionView;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)refreshControlValueChanged:(UIRefreshControl * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The default collection view cell used by the <code>CountriesCollectionController</code> to display the list of countries.
/// This cell contains a single label that is used to display the name of the country.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI25CountryCollectionViewCell")
@interface CountryCollectionViewCell : UICollectionViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified nameLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIActivityIndicatorView;

/// A <code>NibViewController</code> subclass conforming to the <code>LoadableViewController</code>.
/// This view controller is the default design for a loading view controller.
/// It has an activity indicator and a label for a loading message.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI28DefaultLoadingViewController")
@interface DefaultLoadingViewController : NibViewController
/// The activity indicator.
@property (nonatomic, strong) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
/// The loading label
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified loadingLabel;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A <code>NibViewController</code> subclass conforming to the <code>ReloadableViewController</code>.
/// This view controller is the default design for a reload view controller.
/// It has a label for a reload message and a button to execute the reload.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI27DefaultReloadViewController")
@interface DefaultReloadViewController : NibViewController
/// The container of the label and button.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified containerStackView;
/// The reload message label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified messageLabel;
/// The retry button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified retryButton;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

/// A <code>StatefulViewController</code> subclass that manages a generic detail view.
/// This view controller serves as the base design of a detail view.
/// An object conforming to the <code>DetailController</code> protocol is the data provider and action handler of this view controller.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI20DetailViewController")
@interface DetailViewController : StatefulViewController
@property (nonatomic, strong) IBOutlet UIScrollView * _Null_unspecified scrollView;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified labelStackView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified headingLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified subheadingLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified bodyLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified pointsLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified periodLabel;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified actionButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayoutAttributes;

/// A CollectionViewFlowLayout that resembles a table view with dynamic height sizing.
/// This flow layout mimics a table view layout with dynamic height sizing.
/// It has <code>minimumLineSpacing</code> and <code>minimumInteritemSpacing</code> set to 10.
/// Collection view cells used in this layout must override the <code>preferredLayoutAttributesFitting(_:)</code> method to calculate the appropriate height for the cell. One way of doing this is the following:
/// \code
/// override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
///     let layoutAttributes = super.preferredLayoutAttributesFitting(layoutAttributes)
///     layoutIfNeeded()
///     layoutAttributes.frame.size = systemLayoutSizeFitting(UIView.layoutFittingCompressedSize,
///                                                           withHorizontalFittingPriority: .required,
///                                                           verticalFittingPriority: .fittingSizeLevel)
///     return layoutAttributes
/// }
///
/// \endcode
SWIFT_CLASS("_TtC16CheetahLoyaltyUI35DynamicListCollectionViewFlowLayout")
@interface DynamicListCollectionViewFlowLayout : UICollectionViewFlowLayout
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

SWIFT_CLASS("_TtC16CheetahLoyaltyUI17FloatingTextField")
@interface FloatingTextField : UITextField
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic) NSTextAlignment textAlignment;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isEnabled) BOOL enabled;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI25FloatingTextFieldWithIcon")
@interface FloatingTextFieldWithIcon : FloatingTextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI15GrowingTextView")
@interface GrowingTextView : UIScrollView
@property (nonatomic, strong) UIView * _Nullable inputView;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic, readonly) BOOL isFirstResponder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)reloadInputViews;
@end


SWIFT_CLASS("_TtC16CheetahLoyaltyUI16FloatingTextView")
@interface FloatingTextView : GrowingTextView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


/// An <code>AlertEmbeddableViewController</code> that can display
/// a heading message, a subheading message, and a dynamic count of buttons in a <code>UIStackView</code>
SWIFT_CLASS("_TtC16CheetahLoyaltyUI26GenericAlertViewController")
@interface GenericAlertViewController : NibViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headingLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subheadingLabel;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@class UIImagePickerController;

/// A wrapper class setting up the presentation of an <code>UIImagePickerController</code> by a designated view controller. This wrapper class only accepts media types of image or movie.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI20ImagePickerPresenter")
@interface ImagePickerPresenter : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A CollectionViewFlowLayout that resembles a table view.
/// This flow layout mimics a table view layout.
/// It has <code>minimumLineSpacing</code> and <code>minimumInteritemSpacing</code> set to 10.
/// The <code>itemSize</code> is set with the width equal to the collection view frame width minus the left and right section inset,
/// and the height set as the <code>cellHeight</code> property.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI28ListCollectionViewFlowLayout")
@interface ListCollectionViewFlowLayout : UICollectionViewFlowLayout
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
@end


/// A general collection view cell for list content.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI12ListItemCell")
@interface ListItemCell : UICollectionViewCell
/// A container view for all elements except for the activitiy indicator.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
/// An image view for the content.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
/// A stack view holding the title and subtitle label.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified contentStackView;
/// The title label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
/// The subtitle label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified subtitleLabel;
/// A general action button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified actionButton;
/// An activity Indicator for loading content.
@property (nonatomic, strong) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC16CheetahLoyaltyUI26LoadingAlertViewController")
@interface LoadingAlertViewController : NibViewController
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activitityIndicatorView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified loadingLabel;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// This is the default collection view cell used by the <code>MenuCollectionController</code> to display the list of Menu.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI12MenuItemCell")
@interface MenuItemCell : UICollectionViewCell
/// An image view for the content.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified image;
/// The name label.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified name;
/// A container view for the name label.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified nameContainerView;
/// A stack view for the menu list.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified menuStackView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A subclass of <code>CollectionViewController</code> that shows a list of menu items with a log out button.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI18MenuViewController")
@interface MenuViewController : CollectionViewController
/// The log out button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified logOutButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



/// A subclass of <code>CheckBox</code> that serves as a radio button
/// that has an event listener/emitter to other radio buttons
/// within the same group
SWIFT_CLASS("_TtC16CheetahLoyaltyUI11RadioButton")
@interface RadioButton : CheckBox
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// A custom <code>UIButton</code>that serves as a rating button
/// that has an event listener/emitter to other rating buttons
/// within the same group
SWIFT_CLASS("_TtC16CheetahLoyaltyUI12RatingButton")
@interface RatingButton : SelectionButton
- (void)didTapButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;
@class AVCaptureConnection;

/// A <code>NibViewController</code> subclass that scans codes using the device’s camera.
/// This view controller captures codes from the device’s camera.
/// The code is then passed into the <code>captureAction</code> closure property.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI21ScannerViewController")
@interface ScannerViewController : NibViewController <AVCaptureMetadataOutputObjectsDelegate>
- (void)viewDidLayoutSubviews;
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UISegmentedControl;

/// A <code>NibViewController</code> subclass that manages segmented views.
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
/// This includes a segmented control that receives value changed events to change the shown view inside its container view.
/// Data and selection actions are managed by an object conforming to <code>SegmentedController</code> which is assigned to the <code>segmentedController</code> property.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI23SegmentedViewController")
@interface SegmentedViewController : NibViewController
/// The segmented control.
@property (nonatomic, strong) IBOutlet UISegmentedControl * _Null_unspecified segmentedControl;
/// The content view.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



/// The default collection view cell used by the <code>StatesCollectionController</code> to display the list of states.
/// This cell contains a single label that is used to display the name/label of the state.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI23StateCollectionViewCell")
@interface StateCollectionViewCell : UICollectionViewCell
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified nameLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





















































/// An <code>AlertEmbeddableViewController</code> that displays
/// a full screen view that forces/asks the user to upgrade the application to its current version
SWIFT_CLASS("_TtC16CheetahLoyaltyUI26UpgradeCheckViewController")
@interface UpgradeCheckViewController : NibViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified messageTextView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified upgradeNowButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified upgradeLaterButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified photoImageView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class WKNavigation;

/// A <code>NibViewController</code> subclass that displays web content.
/// This view controller holds a <code>WKWebView</code> and a <code>UIProgressView</code>.
/// The progress view is only shown when the web view is loading content.
/// This view controller also conforms to <code>WKNavigationDelegate</code>.
SWIFT_CLASS("_TtC16CheetahLoyaltyUI17WebViewController")
@interface WebViewController : NibViewController <WKNavigationDelegate>
/// The web view.
@property (nonatomic, strong) IBOutlet WKWebView * _Null_unspecified webView;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
