#if TARGET_OS_SIMULATOR
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CheetahLoyaltyUI;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CheetahLoyaltyChallenges",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIScrollView;
@class UIButton;
@class UIImageView;
@class UILabel;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges29AvatarChallengeViewController")
@interface AvatarChallengeViewController : NibViewController
/// Scroll view of the view.
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified scrollView;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified submitButton;
/// Image view that displays the image.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Upload label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified uploadLabel;
/// Presents the image picker.
- (void)uploadPhoto;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges22BaseChallengeResponder")
@interface BaseChallengeResponder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A <code>NibViewController</code> subclass that manages a generic Challenge Response Detail View.
/// This view controller serves as the base design of a Challenge Response Detail View.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges37ChallengeResponseDetailViewController")
@interface ChallengeResponseDetailViewController : NibViewController
/// Label use for displaying response message.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified responseMessageLabel;
/// Label use for displaying challenge details.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified challengeDetailsLabel;
/// Image of the challenge.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
/// Button for feedback.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified feedButton;
/// Back button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified backButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStackView;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges30CheckInChallengeViewController")
@interface CheckInChallengeViewController : NibViewController
/// Stack view of the view.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
/// Image view for displaying the image.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// The activity indicator.
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicatorView;
/// Header label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headerLabel;
/// Detail label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified detailLabel;
/// Subheader label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subheaderLabel;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified respondButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;
@class WKFrameInfo;
@class WKUserContentController;
@class WKScriptMessage;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges27GameChallengeViewController")
@interface GameChallengeViewController : NibViewController <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
/// View of the game.
@property (nonatomic, strong) IBOutlet WKWebView * _Null_unspecified gameView;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges30GenericChallengeViewController")
@interface GenericChallengeViewController : GenericAlertViewController
/// Stack view of the view.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified containerStackView;
/// Activity indicator of the view.
@property (nonatomic, strong) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
/// Message container view of the view.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified messageContainerView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class GrowingTextView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges28MediaChallengeViewController")
@interface MediaChallengeViewController : NibViewController
/// View that displays the video selected.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoContainerView;
/// Growing Text View that is used for inputting a description.
@property (nonatomic, weak) IBOutlet GrowingTextView * _Null_unspecified textView;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified submitButton;
/// Image view that displays the image selected.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Action label for displaying the type of media to be uploaded.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified actionLabel;
/// Scroll view of the view.
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified scrollView;
- (void)viewDidDisappear:(BOOL)animated;
/// Presents the image picker
- (void)uploadMedia;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;
@class UIPanGestureRecognizer;
@class UITapGestureRecognizer;
@class UIGestureRecognizer;
@class UITouch;
@class UIPickerView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges27MemeChallengeViewController")
@interface MemeChallengeViewController : NibViewController <UIGestureRecognizerDelegate, UIPickerViewDataSource, UIPickerViewDelegate, UITextFieldDelegate>
/// Textfied that is used for putting caption on a <code>separateFromImage</code> subtype.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified captionSeparateFromImageTextField;
/// Textfield used for selecting <code>font size</code> of the caption.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified fontTextField;
/// Button used for selecting <code>color</code> for the caption
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified colorPickerButton;
/// View where captions and images are being add.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified canvasView;
/// Image view for the meme to respond.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Textfied that is used for putting caption on a <code>overImage</code> subtype.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified captionTextField;
/// Button for adding the text on the <code>captionTextField</code> on the <code>canvasView</code>.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified addButton;
/// Parent view for <code>overImage</code> subtype views.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified captionEditorView;
- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)viewWillAppear:(BOOL)animated;
/// Updates the location of the panned caption.
- (void)didPanCaption:(UIPanGestureRecognizer * _Nonnull)gestureRecognizer;
/// Selects the tapped caption.
- (void)didTapCaption:(UITapGestureRecognizer * _Nonnull)gestureRecognizer;
/// Resets the view.
- (void)dismissKeyboard;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges17MultiQuestionCell")
@interface MultiQuestionCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPageControl;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges36MultiQuestionChallengeViewController")
@interface MultiQuestionChallengeViewController : CollectionViewController
/// Page Control of the view.
@property (nonatomic, weak) IBOutlet UIPageControl * _Null_unspecified pageControl;
/// Stack view of buttons.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified buttonsStackView;
/// Button for changing the page.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified previousButton;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified respondButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges25SurveyResponderController")
@interface SurveyResponderController : NSObject
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
/// Called when the respond button is pressed.
- (void)respondButtonPressed:(UIButton * _Nonnull)sender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges39MultipleChoiceSurveyResponderController")
@interface MultipleChoiceSurveyResponderController : SurveyResponderController <UITextFieldDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges32NumericSurveyResponderController")
@interface NumericSurveyResponderController : SurveyResponderController <UITextFieldDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges33PreferenceChallengeViewController")
@interface PreferenceChallengeViewController : CollectionViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges30ProfileChallengeViewController")
@interface ProfileChallengeViewController : CollectionViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges31RatingSurveyResponderController")
@interface RatingSurveyResponderController : SurveyResponderController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UIActivityViewController;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges27ReferralChallengeController")
@interface ReferralChallengeController : NSObject <UIActivityItemSource>
- (id _Nonnull)activityViewControllerPlaceholderItem:(UIActivityViewController * _Nonnull)activityViewController SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)activityViewController:(UIActivityViewController * _Nonnull)activityViewController itemForActivityType:(UIActivityType _Nullable)activityType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activityViewController:(UIActivityViewController * _Nonnull)activityViewController subjectForActivityType:(UIActivityType _Nullable)activityType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges29SurveyChallengeViewController")
@interface SurveyChallengeViewController : CollectionViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UICollectionViewLayoutAttributes;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges16SurveyChoiceCell")
@interface SurveyChoiceCell : UICollectionViewCell
/// Container view of the cell.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
/// Stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
/// Image view of the cell.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Selection stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified selectionStackView;
/// Text field of the cell.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified textField;
- (void)awakeFromNib;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges16SurveyDetailCell")
@interface SurveyDetailCell : UICollectionViewCell
/// Container view of the cell.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
/// Stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
/// Image view of the cell.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Question label of the cell.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified questionLabel;
/// Description label of the cell.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified descriptionLabel;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges16SurveyRatingCell")
@interface SurveyRatingCell : UICollectionViewCell
/// Container view of the cell.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
/// Stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges17SurveyRespondCell")
@interface SurveyRespondCell : UICollectionViewCell
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified respondButton;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges19SurveyTextFieldCell")
@interface SurveyTextFieldCell : UICollectionViewCell
/// Text field of the cell.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified textField;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges18SurveyTextViewCell")
@interface SurveyTextViewCell : UICollectionViewCell
/// Text view of the cell.
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified textView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges29TextSurveyResponderController")
@interface TextSurveyResponderController : SurveyResponderController <UITextViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// A <code>NibViewController</code> subclass that manages the View Content View Controller.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges25ViewContentViewController")
@interface ViewContentViewController : StatefulViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified actionButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#else
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CheetahLoyaltyUI;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CheetahLoyaltyChallenges",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIScrollView;
@class UIButton;
@class UIImageView;
@class UILabel;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges29AvatarChallengeViewController")
@interface AvatarChallengeViewController : NibViewController
/// Scroll view of the view.
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified scrollView;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified submitButton;
/// Image view that displays the image.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Upload label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified uploadLabel;
/// Presents the image picker.
- (void)uploadPhoto;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges22BaseChallengeResponder")
@interface BaseChallengeResponder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A <code>NibViewController</code> subclass that manages a generic Challenge Response Detail View.
/// This view controller serves as the base design of a Challenge Response Detail View.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges37ChallengeResponseDetailViewController")
@interface ChallengeResponseDetailViewController : NibViewController
/// Label use for displaying response message.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified responseMessageLabel;
/// Label use for displaying challenge details.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified challengeDetailsLabel;
/// Image of the challenge.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imageView;
/// Button for feedback.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified feedButton;
/// Back button.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified backButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStackView;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges30CheckInChallengeViewController")
@interface CheckInChallengeViewController : NibViewController
/// Stack view of the view.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
/// Image view for displaying the image.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// The activity indicator.
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicatorView;
/// Header label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headerLabel;
/// Detail label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified detailLabel;
/// Subheader label of the view.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subheaderLabel;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified respondButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;
@class WKFrameInfo;
@class WKUserContentController;
@class WKScriptMessage;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges27GameChallengeViewController")
@interface GameChallengeViewController : NibViewController <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
/// View of the game.
@property (nonatomic, strong) IBOutlet WKWebView * _Null_unspecified gameView;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges30GenericChallengeViewController")
@interface GenericChallengeViewController : GenericAlertViewController
/// Stack view of the view.
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified containerStackView;
/// Activity indicator of the view.
@property (nonatomic, strong) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
/// Message container view of the view.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified messageContainerView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class GrowingTextView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges28MediaChallengeViewController")
@interface MediaChallengeViewController : NibViewController
/// View that displays the video selected.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoContainerView;
/// Growing Text View that is used for inputting a description.
@property (nonatomic, weak) IBOutlet GrowingTextView * _Null_unspecified textView;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified submitButton;
/// Image view that displays the image selected.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Action label for displaying the type of media to be uploaded.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified actionLabel;
/// Scroll view of the view.
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified scrollView;
- (void)viewDidDisappear:(BOOL)animated;
/// Presents the image picker
- (void)uploadMedia;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;
@class UIPanGestureRecognizer;
@class UITapGestureRecognizer;
@class UIGestureRecognizer;
@class UITouch;
@class UIPickerView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges27MemeChallengeViewController")
@interface MemeChallengeViewController : NibViewController <UIGestureRecognizerDelegate, UIPickerViewDataSource, UIPickerViewDelegate, UITextFieldDelegate>
/// Textfied that is used for putting caption on a <code>separateFromImage</code> subtype.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified captionSeparateFromImageTextField;
/// Textfield used for selecting <code>font size</code> of the caption.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified fontTextField;
/// Button used for selecting <code>color</code> for the caption
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified colorPickerButton;
/// View where captions and images are being add.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified canvasView;
/// Image view for the meme to respond.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Textfied that is used for putting caption on a <code>overImage</code> subtype.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified captionTextField;
/// Button for adding the text on the <code>captionTextField</code> on the <code>canvasView</code>.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified addButton;
/// Parent view for <code>overImage</code> subtype views.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified captionEditorView;
- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)viewWillAppear:(BOOL)animated;
/// Updates the location of the panned caption.
- (void)didPanCaption:(UIPanGestureRecognizer * _Nonnull)gestureRecognizer;
/// Selects the tapped caption.
- (void)didTapCaption:(UITapGestureRecognizer * _Nonnull)gestureRecognizer;
/// Resets the view.
- (void)dismissKeyboard;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges17MultiQuestionCell")
@interface MultiQuestionCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPageControl;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges36MultiQuestionChallengeViewController")
@interface MultiQuestionChallengeViewController : CollectionViewController
/// Page Control of the view.
@property (nonatomic, weak) IBOutlet UIPageControl * _Null_unspecified pageControl;
/// Stack view of buttons.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified buttonsStackView;
/// Button for changing the page.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified previousButton;
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified respondButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges25SurveyResponderController")
@interface SurveyResponderController : NSObject
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
/// Called when the respond button is pressed.
- (void)respondButtonPressed:(UIButton * _Nonnull)sender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges39MultipleChoiceSurveyResponderController")
@interface MultipleChoiceSurveyResponderController : SurveyResponderController <UITextFieldDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges32NumericSurveyResponderController")
@interface NumericSurveyResponderController : SurveyResponderController <UITextFieldDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges33PreferenceChallengeViewController")
@interface PreferenceChallengeViewController : CollectionViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges30ProfileChallengeViewController")
@interface ProfileChallengeViewController : CollectionViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges31RatingSurveyResponderController")
@interface RatingSurveyResponderController : SurveyResponderController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UIActivityViewController;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges27ReferralChallengeController")
@interface ReferralChallengeController : NSObject <UIActivityItemSource>
- (id _Nonnull)activityViewControllerPlaceholderItem:(UIActivityViewController * _Nonnull)activityViewController SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)activityViewController:(UIActivityViewController * _Nonnull)activityViewController itemForActivityType:(UIActivityType _Nullable)activityType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activityViewController:(UIActivityViewController * _Nonnull)activityViewController subjectForActivityType:(UIActivityType _Nullable)activityType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges29SurveyChallengeViewController")
@interface SurveyChallengeViewController : CollectionViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UICollectionViewLayoutAttributes;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges16SurveyChoiceCell")
@interface SurveyChoiceCell : UICollectionViewCell
/// Container view of the cell.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
/// Stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
/// Image view of the cell.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Selection stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified selectionStackView;
/// Text field of the cell.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified textField;
- (void)awakeFromNib;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges16SurveyDetailCell")
@interface SurveyDetailCell : UICollectionViewCell
/// Container view of the cell.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
/// Stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
/// Image view of the cell.
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
/// Question label of the cell.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified questionLabel;
/// Description label of the cell.
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified descriptionLabel;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges16SurveyRatingCell")
@interface SurveyRatingCell : UICollectionViewCell
/// Container view of the cell.
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
/// Stack view of the cell.
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges17SurveyRespondCell")
@interface SurveyRespondCell : UICollectionViewCell
/// Button that is used for responding to the challenge.
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified respondButton;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges19SurveyTextFieldCell")
@interface SurveyTextFieldCell : UICollectionViewCell
/// Text field of the cell.
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified textField;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;

SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges18SurveyTextViewCell")
@interface SurveyTextViewCell : UICollectionViewCell
/// Text view of the cell.
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified textView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges29TextSurveyResponderController")
@interface TextSurveyResponderController : SurveyResponderController <UITextViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// A <code>NibViewController</code> subclass that manages the View Content View Controller.
/// note:
/// Being a subclass of a <code>NibViewController</code>, an associated nib file is required with outlets connected.
SWIFT_CLASS("_TtC24CheetahLoyaltyChallenges25ViewContentViewController")
@interface ViewContentViewController : StatefulViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified actionButton;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
